//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAbout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResAbout() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResAbout", typeof(ResAbout).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Agnieszka Jaśkiewicz.
        /// </summary>
        public static string AgnesName {
            get {
                return ResourceManager.GetString("AgnesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Poprzez efektywną metodologię i sprawdzone narzędzia pracy, przyczynia się do rozwoju kompetencji ludzi, ułatwiając im osiąganie założonych celów. W przypadku firm, ułatwia pracownikom wdrożenia biznesowe i osiąganie założonych celów biznesowych..
        /// </summary>
        public static string AgnesPart1 {
            get {
                return ResourceManager.GetString("AgnesPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Najważniejszy dla niej jest rezultat wspólnej pracy z klientem, czyli zwrot z inwestycji (ROI). Bo najważniejsze jest to, co zadzieje się w efekcie danego procesu rozwojowego, projektu, warsztatu i na ile rozwijane kompetencje przełożą się na działanie operacyjne i jego efekty. Podczas warsztatów uczestnicy poznają i stosują praktyczne rozwiązania, które łatwo mogą wdrożyć w codziennej pracy..
        /// </summary>
        public static string AgnesPart2 {
            get {
                return ResourceManager.GetString("AgnesPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ma długoletnie doświadczenia w zakresie zarządzania w kraju i za granicą. W kraju i za granicą kończyła też studia. Dwa kierunki studiów magisterskich: psychologię społeczną i filologię romańską. Studiowała również podyplomowo: organizację i zarządzanie przedsiębiorstw oraz zarządzanie zasobami ludzkimi..
        /// </summary>
        public static string AgnesPart3 {
            get {
                return ResourceManager.GetString("AgnesPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jej specjalizacja to zarządzanie efektywnością organizacji i efektywnością osobistą, zasobami ludzkimi, przywództwo i zarządzanie, doradztwo strategiczne..
        /// </summary>
        public static string AgnesPart4 {
            get {
                return ResourceManager.GetString("AgnesPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dotychczasowe doświadczenia w pracy z ludźmi, pozwalają jej powiedzieć, że przyczynia się z sukcesem do rozwoju ludzi i organizacji, inspiruje, ułatwia oraz wskazuje rozwiązania..
        /// </summary>
        public static string AgnesPart5 {
            get {
                return ResourceManager.GetString("AgnesPart5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to „Najbardziej biznesowy HR-owiec, jakiego spotkałem „ – zdaniem jednego z prezesów dużej firmy o ogólnopolskim zasięgu..
        /// </summary>
        public static string AgnesPart6 {
            get {
                return ResourceManager.GetString("AgnesPart6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Prywatnie, szczęśliwa żona i matka. Uwielbia podróże i naukę języków obcych. Rozmowy z ludźmi, gotowanie oraz pieczenie ciast..
        /// </summary>
        public static string AgnesPart7 {
            get {
                return ResourceManager.GetString("AgnesPart7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Łukasz Jaśkiewicz.
        /// </summary>
        public static string LukaszName {
            get {
                return ResourceManager.GetString("LukaszName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Z zamiłowania i wykształcenia, pasjonat IT. Przyczynia się do rozwoju działalności firm poprzez proponowanie sprawdzonych i łatwych w obsłudze rozwiązań informatycznych. Od koncepcji poprzez programowanie i wdrożenie, zapewnia efektywne rozwiązania przyjazne użytkownikom. Z powodzeniem komunikując korzyści i funkcjonalności klientom..
        /// </summary>
        public static string LukaszPart1 {
            get {
                return ResourceManager.GetString("LukaszPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Najważniejszy jest dla niego efekt, który wyniknie ze stosowania zaproponowanych przez niego rozwiązań. Na ile wdrożenie danego produktu przyniesie zwrot z inwestycji danej firmie..
        /// </summary>
        public static string LukaszPart2 {
            get {
                return ResourceManager.GetString("LukaszPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Od wczesnych lat szkolnych i poprzez całe zawodowe życie mieszkał w Niemczech. Najlepsze praktyki przenosi teraz na rynek polski..
        /// </summary>
        public static string LukaszPart3 {
            get {
                return ResourceManager.GetString("LukaszPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Prywatnie, szczęśliwy mąż i ojciec. Uwielbia podróże i literaturę fachową. Rozmowy z ludźmi, smakowanie potraw i ciast żony..
        /// </summary>
        public static string LukaszPart4 {
            get {
                return ResourceManager.GetString("LukaszPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Na potrzeby różnych projektów pracują z nami kompetentni współpracownicy..
        /// </summary>
        public static string Slogan1 {
            get {
                return ResourceManager.GetString("Slogan1", resourceCulture);
            }
        }
    }
}
