//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBISoft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResBISoft() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResBISoft", typeof(ResBISoft).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dzięki naszym analizom i oprogramowaniu, zapewnimy klientom oczekiwane narzędzia pomocne w efektywnym zarządzaniu firmą. Zapewnimy szybką i skuteczną informację zarządczą do podejmowania kluczowych decyzji w firmie. Co z kolei bezpośrednio przekłada się na większy zysk firmy..
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rozwiązania są zawsze spersonalizowane do potrzeb danego klienta. Z czujnym wsparciem i koniecznym zaangażowanie w tych obszarach, które często lekceważy albo zaniedbuje konkurencja: a są to głównie pilotaż, potem wdrożenie oraz uaktualnianie danych po uwagach zgłaszanych przez odbiorców..
        /// </summary>
        public static string AdvantagesText2 {
            get {
                return ResourceManager.GetString("AdvantagesText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Oszczędność czasu i innych zasobów klienta oraz w średniej i długiej perspektywie oszczędność budżetu firmy..
        /// </summary>
        public static string BenefitsText1 {
            get {
                return ResourceManager.GetString("BenefitsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Analizy Business Intelligence polegają na przekazaniu know-how (jak dokonywać analiz) i wizualizacji wszelkiego rodzaju mierników efektywności dotyczących danego obszaru działania biznesowego, mając na celu śledzenie (monitorowanie) zakładanego postępu rozwoju i zwiększenia efektywności. Analizy mają na celu implementację w firmach wczesnego systemu ostrzegania, jeśli założone wskaźniki nie są osiągane. Zawsze służą zbieraniu i analizie danych oraz wyciąganiu wniosków w postaci tzw. informacji zarządczej..
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Business Intelligence to także platformy analityczno-raportowe, hurtownie danych i procesy integracji danych, systemy planowania i budżetowania oraz systemy wspierające zarządzanie efektywnością przedsiębiorstwa (Performance Management), rozwiązania wspierające zarządzanie oparte o Balanced Scorecard i zarządzanie przez cele..
        /// </summary>
        public static string CharacteristicsText2 {
            get {
                return ResourceManager.GetString("CharacteristicsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Oprogramowanie dla firm jest zawsze szyte na miarę. Jest ono pomocne w procesie pracy doradczej i konsultingowej, jako sposób rozwiązania danego problemu biznesowego. Jest to usługa wpisana w dany proces biznesowy, poprzedzona pilotażem, uwzględniająca wymogi biznesowe i wymogi funkcjonalne klientów..
        /// </summary>
        public static string CharacteristicsText3 {
            get {
                return ResourceManager.GetString("CharacteristicsText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Proces obsługi klienta opiera się na rozpoznaniu i analizie potrzeb, wdrożeniu rozwiązania i opiece serwisowej..
        /// </summary>
        public static string CharacteristicsText4 {
            get {
                return ResourceManager.GetString("CharacteristicsText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady analiz biznesowych.
        /// </summary>
        public static string Example1Header {
            get {
                return ResourceManager.GetString("Example1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Analiza wyników sprzedaży.
        /// </summary>
        public static string Example1Item1 {
            get {
                return ResourceManager.GetString("Example1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Analiza z działań rozwojowych prowadzonych przez dział HR.
        /// </summary>
        public static string Example1Item2 {
            get {
                return ResourceManager.GetString("Example1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Analiza rodzaju i częstotliwości feedback’u klientów.
        /// </summary>
        public static string Example1Item3 {
            get {
                return ResourceManager.GetString("Example1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Analiza sprawności działania oprogramowania firmowego.
        /// </summary>
        public static string Example1Item4 {
            get {
                return ResourceManager.GetString("Example1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady aplikacji biznesowych.
        /// </summary>
        public static string Example2Header {
            get {
                return ResourceManager.GetString("Example2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aplikacja do przeprowadzania oceny pracowniczej w firmie.
        /// </summary>
        public static string Example2Item1 {
            get {
                return ResourceManager.GetString("Example2Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aplikacja do zarządzania kompetencjami w organizacji.
        /// </summary>
        public static string Example2Item2 {
            get {
                return ResourceManager.GetString("Example2Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aplikacja do zarządzania celami premiowymi w firmie.
        /// </summary>
        public static string Example2Item3 {
            get {
                return ResourceManager.GetString("Example2Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aplikacja do planowania rozwoju pracowników, zarządzania ich szkoleniami.
        /// </summary>
        public static string Example2Item4 {
            get {
                return ResourceManager.GetString("Example2Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aplikacja do zarządzania sukcesją i planem następstw w firmie.
        /// </summary>
        public static string Example2Item5 {
            get {
                return ResourceManager.GetString("Example2Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Business Intelligence&lt;br /&gt;.
        /// </summary>
        public static string HeaderPart1 {
            get {
                return ResourceManager.GetString("HeaderPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string HeaderPart2 {
            get {
                return ResourceManager.GetString("HeaderPart2", resourceCulture);
            }
        }
    }
}
