//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCoachingExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResCoachingExamples() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResCoachingExamples", typeof(ResCoachingExamples).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Personal / Life Coaching.
        /// </summary>
        public static string Example1Header {
            get {
                return ResourceManager.GetString("Example1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Planowanie życia.
        /// </summary>
        public static string Example1Item1 {
            get {
                return ResourceManager.GetString("Example1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rozwiązywanie problemów z dziećmi, nastolatkami i studentami.
        /// </summary>
        public static string Example1Item10 {
            get {
                return ResourceManager.GetString("Example1Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wypracowywanie wizji życia.
        /// </summary>
        public static string Example1Item2 {
            get {
                return ResourceManager.GetString("Example1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Relacje z innymi ludźmi.
        /// </summary>
        public static string Example1Item3 {
            get {
                return ResourceManager.GetString("Example1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Życie duchowe.
        /// </summary>
        public static string Example1Item4 {
            get {
                return ResourceManager.GetString("Example1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Związki (dla osób samotnych, par i rodzin).
        /// </summary>
        public static string Example1Item5 {
            get {
                return ResourceManager.GetString("Example1Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dbanie o zdrowie i urodę.
        /// </summary>
        public static string Example1Item6 {
            get {
                return ResourceManager.GetString("Example1Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rozwijanie kreatywności.
        /// </summary>
        public static string Example1Item7 {
            get {
                return ResourceManager.GetString("Example1Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Uzyskiwanie wolności finansowej.
        /// </summary>
        public static string Example1Item8 {
            get {
                return ResourceManager.GetString("Example1Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Lepsza organizacja życia.
        /// </summary>
        public static string Example1Item9 {
            get {
                return ResourceManager.GetString("Example1Item9", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Pomoc w rozwiązywaniu problemów związanych z życiem osobistym i relacjami, poprzez konsultacje indywidualne. Konsultacja indywidualne - to spotkanie dla tych, którzy mają konkretne problemy i chcą je rozwiązać. To spotkanie dla tych, dla których rozmowa w cztery oczy ma kluczowe znaczenie, którzy w bezpiecznych warunkach chcą uzyskać wsparcie i znaleźć rozwiązanie dla swojego problemu (np. w zakresie: radzenia sobie ze zmianą, radzenia sobie z kryzysem w życiu, trudności emocjonalnych, zaburzonego obrazu po [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Example1Text1 {
            get {
                return ResourceManager.GetString("Example1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Career / Transition Coaching.
        /// </summary>
        public static string Example2Header {
            get {
                return ResourceManager.GetString("Example2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Osoby zmieniającej ścieżkę kariery.
        /// </summary>
        public static string Example2Item1 {
            get {
                return ResourceManager.GetString("Example2Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Osoby stającej przed decyzjami zawodowymi.
        /// </summary>
        public static string Example2Item2 {
            get {
                return ResourceManager.GetString("Example2Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Osoby pracującej w dużej firmie/korporacji lub zastanawiającej się nad podjęciem tam pracy.
        /// </summary>
        public static string Example2Item3 {
            get {
                return ResourceManager.GetString("Example2Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Osoby borykającej się z decyzją o odejściu z dużej firmy/korporacji.
        /// </summary>
        public static string Example2Item4 {
            get {
                return ResourceManager.GetString("Example2Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pomoc dotycząca rozwoju zawodowego, kolejnych etapów na drodze zawodowej. Np. dla:.
        /// </summary>
        public static string Example2Text1 {
            get {
                return ResourceManager.GetString("Example2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Small Business Coaching.
        /// </summary>
        public static string Example3Header {
            get {
                return ResourceManager.GetString("Example3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Właściciele i menedżerowie w małych firmach.
        /// </summary>
        public static string Example3Item1 {
            get {
                return ResourceManager.GetString("Example3Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Firmy w okresie „rozruchowym”.
        /// </summary>
        public static string Example3Item2 {
            get {
                return ResourceManager.GetString("Example3Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Osoby prowadzące samodzielną działalność gospodarczą.
        /// </summary>
        public static string Example3Item3 {
            get {
                return ResourceManager.GetString("Example3Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ludzie prowadzący działalność gospodarczą w domu.
        /// </summary>
        public static string Example3Item4 {
            get {
                return ResourceManager.GetString("Example3Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przedstawiciele kadry zarządzającej chcący odejść z dużych korporacji i założyć własną działalność.
        /// </summary>
        public static string Example3Item5 {
            get {
                return ResourceManager.GetString("Example3Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pomoc dotycząca prowadzenia własnej działalności gospodarczej i małych firm. Przykładowi odbiorcy usługi:.
        /// </summary>
        public static string Example3Text1 {
            get {
                return ResourceManager.GetString("Example3Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Executive - Corporate Coaching.
        /// </summary>
        public static string Example4Header {
            get {
                return ResourceManager.GetString("Example4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Działy kadrowe zainteresowane wykorzystaniem coacha spoza organizacji.
        /// </summary>
        public static string Example4Item1 {
            get {
                return ResourceManager.GetString("Example4Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wyższa  kadra zarządzająca, menedżerowie i specjaliści, którzy chcieliby skorzystać z usług coacha.
        /// </summary>
        public static string Example4Item2 {
            get {
                return ResourceManager.GetString("Example4Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Firmy chcące wprowadzić coaching, jako sposób rozwoju ludzi bądź kulturę coachingową w pracy menedżera / coaching&apos;owy styl pracy.
        /// </summary>
        public static string Example4Item3 {
            get {
                return ResourceManager.GetString("Example4Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Firmy, które pragną przeszkolić swoich menedżerów z zakresu coaching&apos;u.
        /// </summary>
        public static string Example4Item4 {
            get {
                return ResourceManager.GetString("Example4Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to W celu wyeliminowania lub pomocy w przypadku wypalenia zawodowego.
        /// </summary>
        public static string Example4Item5 {
            get {
                return ResourceManager.GetString("Example4Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Firmy zainteresowane warsztatami z zakresu coaching&apos;u.
        /// </summary>
        public static string Example4Item6 {
            get {
                return ResourceManager.GetString("Example4Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Firmy chcące wspomóc pracowników coaching&apos;iem w jednym z poniższych obszarów: planowanie strategiczne, proces re-engineeringu, budowanie i rozwój zespołów, rozwój w wyniku rozmowy/oceny kompetencyjnej.
        /// </summary>
        public static string Example4Item7 {
            get {
                return ResourceManager.GetString("Example4Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Praca z kadrą zarządzającą przedsiębiorstw. Nastawiona na rozwój biznesu, rozumianego, jako przedsiębiorstwo, na wzrost efektywności zarządzającego. Również pomoc w rozwiązywaniu problemów związanych z pracą zawodową (np. w zakresie: trudności z przełożonym, rozwoju zawodowego, trudności w realizacji celów biznesowych, problemów w zakresie komunikacji z otoczeniem). Również pomoc podczas wprowadzenia pracownika do nowej roli zawodowej (np. w przypadku awansu wewnętrznego ze specjalisty na stanowisko menedże [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Example4Text1 {
            get {
                return ResourceManager.GetString("Example4Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mentoring HR.
        /// </summary>
        public static string Example5Header {
            get {
                return ResourceManager.GetString("Example5Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Mentoring HR (uczenie się przez doświadczenie i dawanie przykładu) w budowaniu autorytetu menedżera HR oraz budowaniu i rozwoju profesjonalnego zespołu mu podległego. Lub dla specjalisty HR – budowanie jego profesjonalizmu zawodowego w obszarze HR. Polecamy osobom rozpoczynającym pracę, jako szef personalny. Pomagamy im rozwijać wiedzę, umiejętności i kompetencje metodą uczenia się przez doświadczenie. Dajemy unikalną możliwość wykorzystania eksperckiej wiedzy i doświadczeń mentora do realizacji stojących p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Example5Text1 {
            get {
                return ResourceManager.GetString("Example5Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Proces mentoring’owy może być poprzedzony shadowing’iem (jednodniową, kilkugodzinną obserwacją w miejscu pracy), zakończoną udzieleniem informacji zwrotnej (skoncentrowanej na zaobserwowanych faktach)..
        /// </summary>
        public static string Example5Text2 {
            get {
                return ResourceManager.GetString("Example5Text2", resourceCulture);
            }
        }
    }
}
