//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCoaching {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResCoaching() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResCoaching", typeof(ResCoaching).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Podczas spotkania coaching&apos;owego (sesji), coach poprzez zadawane pytania i sposób rozmowy powoduje, że coachowany odkrywa istotne przyczyny swych zachowań, które wydają się mało użyteczne. Jest to punkt wyjścia do wypracowania nowych rozwiązań – szybkiej i trwałej zmiany..
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dzięki ofercie coaching&apos;u zapewniamy odbiorcom biznesowym i indywidualnym najlepszą wiedzę i narzędzia w celu rozwiązania ich problemów i zrealizowania celów ustalonych wspólnie do pracy podczas sesji coaching&apos;owych..
        /// </summary>
        public static string AdvantagesText2 {
            get {
                return ResourceManager.GetString("AdvantagesText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Podczas procesu mentoring&apos;u, doświadczony HR-owiec udziela rad/inspiracji/sugestii, podaje praktyczne przykłady klientowi mniej doświadczonemu. Jest cały czas skoncentrowany na zadaniach, które realizuje klient, na problemach, których doświadcza, na tym co (nie) chce/(nie) potrafi. Demonstruje również zachowania, które stanowią wzorzec do naśladowania. Wspomaga w ten sposób rozwój kompetencji. Poprzedza to obserwacją w miejscu pracy i informacją zwrotną z obserwacji..
        /// </summary>
        public static string AdvantagesText3 {
            get {
                return ResourceManager.GetString("AdvantagesText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dzięki mentoring&apos;owi zapewnimy odbiorcom biznesowym i indywidualnym ekspercką wiedzę, umiejętności oraz przykłady najlepszych rozwiązań poparte doświadczeniem, tak aby w wyniku nauki przez doświadczenie zdobyli pożądaną wiedzę, umiejętności, zachowania i postawy..
        /// </summary>
        public static string AdvantagesText4 {
            get {
                return ResourceManager.GetString("AdvantagesText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dzięki naszemu know-how klienci znajdują rozwiązania swoich problemów. Ich osobiste i biznesowe działania zostają zoptymalizowane. W przypadku celów biznesowych, zostają one zrealizowane przez klienta, co obliczamy za pomocą wskaźników. A to z kolei ma bezpośrednie przełożenie na wyniki finansowe firmy..
        /// </summary>
        public static string BenefitsText1 {
            get {
                return ResourceManager.GetString("BenefitsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Coaching jest interaktywnym procesem, który pomaga pojedynczym osobom lub organizacjom w rozwiązaniu problemów, przyspieszeniu tempa rozwoju i polepszeniu efektów działania. Pracujemy z klientami nad zagadnieniami związanymi z biznesem, rozwojem kariery, finansami, zdrowiem i relacjami interpersonalnymi. Dzięki coachingowi klienci ustalają konkretne cele, optymalizują swoje działania, podejmują trafniejsze i szybsze decyzje i pełniej korzystają ze swoich naturalnych umiejętności, dotychczas zdobytej wiedzy  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zakładamy, że każdy z nas jest z natury kreatywny i może sobie pomóc sam. Zadanie nasze polega na wydobyciu tych umiejętności, zasobów i kreatywności, które klient już posiada.
        ///                    Nasza rola polega także na zadaniu właściwych pytań we właściwym czasie oraz na dzieleniu się informacją zwrotną. Odpowiedzialność za podjęcie decyzji oraz podjęcie działań pozostaje w rękach klienta..
        /// </summary>
        public static string CharacteristicsText2 {
            get {
                return ResourceManager.GetString("CharacteristicsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady prowadzonego przez nas Coaching&apos;u i Mentoring&apos;u.
        /// </summary>
        public static string ExamplesHeader {
            get {
                return ResourceManager.GetString("ExamplesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Personal / Life Coaching.
        /// </summary>
        public static string ExamplesItem1 {
            get {
                return ResourceManager.GetString("ExamplesItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Career / Transition Coaching.
        /// </summary>
        public static string ExamplesItem2 {
            get {
                return ResourceManager.GetString("ExamplesItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Small Business Coaching.
        /// </summary>
        public static string ExamplesItem3 {
            get {
                return ResourceManager.GetString("ExamplesItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Executive / Corporate Coaching.
        /// </summary>
        public static string ExamplesItem4 {
            get {
                return ResourceManager.GetString("ExamplesItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mentoring HR + Shadowing.
        /// </summary>
        public static string ExamplesItem5 {
            get {
                return ResourceManager.GetString("ExamplesItem5", resourceCulture);
            }
        }
    }
}
