//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResContact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResContact() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResContact", typeof(ResContact).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Anruf.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Handy.
        /// </summary>
        public static string Cellular {
            get {
                return ResourceManager.GetString("Cellular", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to kontakt@helobis.de.
        /// </summary>
        public static string ContactEmailGermany {
            get {
                return ResourceManager.GetString("ContactEmailGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kontakt w Niemczech.
        /// </summary>
        public static string ContactHeaderGermany {
            get {
                return ResourceManager.GetString("ContactHeaderGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kontakt w Polsce.
        /// </summary>
        public static string ContactHeaderPoland {
            get {
                return ResourceManager.GetString("ContactHeaderPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Folgen Sie uns auf.
        /// </summary>
        public static string FollowMe {
            get {
                return ResourceManager.GetString("FollowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LinkedIn Profil.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Standort.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to info@helobis.pl.
        /// </summary>
        public static string MailAdrress {
            get {
                return ResourceManager.GetString("MailAdrress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nachricht.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to +49 176 966 34 9 34.
        /// </summary>
        public static string MobileNumerGermany {
            get {
                return ResourceManager.GetString("MobileNumerGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to +48 501 017 017.
        /// </summary>
        public static string MobileNumerPolandAgnieszka {
            get {
                return ResourceManager.GetString("MobileNumerPolandAgnieszka", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to +48 500 368 363.
        /// </summary>
        public static string MobileNumerPolandLukasz {
            get {
                return ResourceManager.GetString("MobileNumerPolandLukasz", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to +49 261 1600 4967.
        /// </summary>
        public static string PhoneNumberGermany {
            get {
                return ResourceManager.GetString("PhoneNumberGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to +48 22 121 33 74.
        /// </summary>
        public static string PhoneNumberPoland {
            get {
                return ResourceManager.GetString("PhoneNumberPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nachricht senden.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Social Media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rufen Sie uns an oder schreiben Sie eine Nachricht.
        /// </summary>
        public static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
    }
}
