//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResConsulting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResConsulting() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResConsulting", typeof(ResConsulting).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zapewniamy odbiorcom biznesowym ekspercką wiedzę, przykłady najlepszych rozwiązań i benchmarki z obszaru zarządzania przedsiębiorstwem i działem personalnym/HR w firmie. Pokazujemy praktyczne umiejętności i zachowania, dajemy konkretne przykłady zastosowań dostosowane do specyfiki firmy i klienta..
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Nasi klienci biznesowi pracują bardziej efektywnie w obszarze zarządzania projektami, zarządzania zmianami i w obliczu wyzwań, które przed nimi postawiono. Realizują swoje zadania zawodowe (najczęściej określone w formie celów premiowych), za które otrzymują określoną premię. Oraz realizują swoje cele biznesowe (finansowe), bezpośrednio przekładające się na mierniki efektywności, takie jak np.: konkretne mierniki przypisane do każdego projektu, realizują założenia strategii firmy w obszarze wdrożenia zmian, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BenefitsText1 {
            get {
                return ResourceManager.GetString("BenefitsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Oferowane przez nas doradztwo i konsulting polega na zapewnieniu ekspertyzy i rozwiązań problemów biznesowych oraz na dostarczeniu pomocy w rozwoju biznesu, jako całości, polepszeniu jego wyników ekonomicznych..
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Efektywność naszego działania zwiększa się poprzez zastosowanie odpowiedniej kompilacji produktów i usług z naszej oferty w zależności od potrzeb klienta oraz praktycznych rozwiązań, takich jak oprogramowanie, testy psychometryczne i analizy Business Intelligence..
        /// </summary>
        public static string CharacteristicsText2 {
            get {
                return ResourceManager.GetString("CharacteristicsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dla członków zarządów firm, dyrektorów, menedżerów.
        /// </summary>
        public static string Example1Header {
            get {
                return ResourceManager.GetString("Example1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Budowanie strategii firmy.
        /// </summary>
        public static string Example1Item1 {
            get {
                return ResourceManager.GetString("Example1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie zmianami strukturalnymi organizacji.
        /// </summary>
        public static string Example1Item2 {
            get {
                return ResourceManager.GetString("Example1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie kulturą organizacyjną.
        /// </summary>
        public static string Example1Item3 {
            get {
                return ResourceManager.GetString("Example1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie zmianami w organizacji.
        /// </summary>
        public static string Example1Item4 {
            get {
                return ResourceManager.GetString("Example1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Interwencje kryzysowe w biznesie.
        /// </summary>
        public static string Example1Item5 {
            get {
                return ResourceManager.GetString("Example1Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie procesami biznesowymi.
        /// </summary>
        public static string Example1Item6 {
            get {
                return ResourceManager.GetString("Example1Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dla dyrektorów i menedżerów zarządzających HR’em i działami personalnymi w firmach.
        /// </summary>
        public static string Example2Header {
            get {
                return ResourceManager.GetString("Example2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strategia personalna, polityki, systemy, narzędzia, procesy, wskaźniki efektywności HR, regulaminy i procedury w służbie strategii biznesowej firmy.
        /// </summary>
        public static string Example2Item1 {
            get {
                return ResourceManager.GetString("Example2Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie rozwojem i szkoleniami w organizacji w służbie biznesu i ROI.
        /// </summary>
        public static string Example2Item2 {
            get {
                return ResourceManager.GetString("Example2Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie przez kompetencje i zarządzanie przez cele oraz efektywne systemy premiowania.
        /// </summary>
        public static string Example2Item3 {
            get {
                return ResourceManager.GetString("Example2Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie talentami, sukcesją i ścieżkami karier.
        /// </summary>
        public static string Example2Item4 {
            get {
                return ResourceManager.GetString("Example2Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outplacement - monitorowane zwolnienia grupowe i indywidualne.
        /// </summary>
        public static string Example2Item5 {
            get {
                return ResourceManager.GetString("Example2Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady obszarów doradztwa biznesowego i konsultingu.
        /// </summary>
        public static string ExamplesHeader {
            get {
                return ResourceManager.GetString("ExamplesHeader", resourceCulture);
            }
        }
    }
}
