//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResHeaders() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResHeaders", typeof(ResHeaders).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zalety.
        /// </summary>
        public static string Advantages {
            get {
                return ResourceManager.GetString("Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zalety i Korzyści.
        /// </summary>
        public static string AdvantagesAndBenefits {
            get {
                return ResourceManager.GetString("AdvantagesAndBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Korzyści.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to BI i Oprogramowanie.
        /// </summary>
        public static string BISoft {
            get {
                return ResourceManager.GetString("BISoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Business Intelligence i Oprogramowanie.
        /// </summary>
        public static string BISoftLong {
            get {
                return ResourceManager.GetString("BISoftLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Charakterystyka.
        /// </summary>
        public static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Coaching.
        /// </summary>
        public static string Coaching {
            get {
                return ResourceManager.GetString("Coaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Consulting.
        /// </summary>
        public static string Consulting {
            get {
                return ResourceManager.GetString("Consulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Doradztwo Biznesowe i Konsulting.
        /// </summary>
        public static string ConsultingConsulting {
            get {
                return ResourceManager.GetString("ConsultingConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outplacement.
        /// </summary>
        public static string Outplacement {
            get {
                return ResourceManager.GetString("Outplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outsourcing.
        /// </summary>
        public static string Outsourcing {
            get {
                return ResourceManager.GetString("Outsourcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Szkolenia.
        /// </summary>
        public static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
    }
}
