//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResOutsourcing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResOutsourcing() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResOutsourcing", typeof(ResOutsourcing).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outsourcing to praktyczna pomoc dla firm nieposiadających działów personalnych polegająca na zaspokojeniu ich potrzeb dotyczących obsługi i rozwoju pracowników. Brak konieczności posiadania zasobów własnych w obszarze HR i przez to oszczędność etatów i kosztów personelu dla firmy. Dostarczenie przez nas sprawdzonych rozwiązań na rynku..
        /// </summary>
        public static string AdvantagesAndBenefitsText1 {
            get {
                return ResourceManager.GetString("AdvantagesAndBenefitsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outsourcing strategicznej funkcji personalnej to usługa polegająca na zleceniu nam stworzenia i realizacji strategii, polityk, procesów, procedur, narzędzi HR niezbędnych do rozwoju firmy i kontynuowania działalności biznesowej. Rekomendujemy ją małym i średnim firmom, które nie posiadają działów personalnych bądź są one skoncentrowane na działalności administracyjnej (kadry i płace). Usługę porównać można do działania, jako „zewnętrzny” Dyrektor Personalny..
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady Outsourcing&apos;u.
        /// </summary>
        public static string ExamplesBoxHeder {
            get {
                return ResourceManager.GetString("ExamplesBoxHeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zlecenie wykonania analizy potrzeb rozwojowych pracowników, zbudowanie indywidualnych i grupowych planów rozwoju i wsparcie w ich realizacji.
        /// </summary>
        public static string ExamplesBoxItem1 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Opracowanie planu działań dla kluczowej kadry menedżerskiej w celu osiągnięcia lepszych wyników biznesowych.
        /// </summary>
        public static string ExamplesBoxItem2 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zbudowanie strategii personalnej firmy.
        /// </summary>
        public static string ExamplesBoxItem3 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Opracowanie procesów HR – owych „miękkich” (poza kadrami i płacami).
        /// </summary>
        public static string ExamplesBoxItem4 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnoza/audyt kompetencyjny organizacji.
        /// </summary>
        public static string ExamplesBoxItem5 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem5", resourceCulture);
            }
        }
    }
}
