//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResOutplacement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResOutplacement() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResOutplacement", typeof(ResOutplacement).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przejęcie negatywnych emocji zwalnianych przez firmę zewnętrzną i możliwość skupienia się firmy (zleceniodawcy) na działalności biznesowej a nie rozładowywaniu istniejącego napięcia u zwalnianych. Obiektywne spojrzenie na rynek i kompetencje zwalnianych..
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zapewniamy firmom zachowanie klimatu społecznego na właściwym poziomie i zachowanie dobrej opinii na rynku – mimo zwolnień pracowników. Zapewniamy oszczędność kosztów na wypadek ewentualnych procesów sądowych z pracownikami..
        /// </summary>
        public static string BenefitsText1 {
            get {
                return ResourceManager.GetString("BenefitsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przykłady Outplacement&apos;u.
        /// </summary>
        public static string Box1Header {
            get {
                return ResourceManager.GetString("Box1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Opracowanie i wdrożenie koncepcji procesu zwolnień grupowych monitorowanych wraz z procesem komunikacji do pracowników.
        /// </summary>
        public static string Box1Item1 {
            get {
                return ResourceManager.GetString("Box1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Opracowanie planu działań dla zwalnianego dyrektora.
        /// </summary>
        public static string Box1Item2 {
            get {
                return ResourceManager.GetString("Box1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Opracowanie koncepcji i planu spotkań indywidualnych w ramach monitorowanych zwolnień grupowych.
        /// </summary>
        public static string Box1Item3 {
            get {
                return ResourceManager.GetString("Box1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Outplacement to monitorowane zwolnienia indywidualne bądź grupowe. Monitorowanie zwolnienia stanowi praktyczny program wsparcia dla zwalnianego/odchodzącego z firmy pracownika. Wsparcie obejmuje pracę z emocjami związaną z sytuacją spowodowaną utratą pracy oraz przygotowanie zwalnianego pracownika do znalezienia i podjęcia nowej pracy. To również zarządzenie całym procesem zwolnień poprzez zaplanowanie i przygotowanie konkretnej sekwencji działań dla tych pracowników, którzy w firmie zostają..
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Działania te mogą objąć np.: spotkania indywidualne z odchodzącymi pracownikami, spotkania grupowe z pracownikami pozostającymi w firmie, negocjacje z partnerami społecznymi, aktywizację zawodową zwalnianych wraz ze szkoleniami związanymi ze zmianą zawodu, analizę rynku pracy danego obszaru zatrudnienia wraz z poszukiwaniem nowych miejsc pracy dla zwalnianych..
        /// </summary>
        public static string CharacteristicsText2 {
            get {
                return ResourceManager.GetString("CharacteristicsText2", resourceCulture);
            }
        }
    }
}
