//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductOverview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResProductOverview() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResProductOverview", typeof(ResProductOverview).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Misja i Wizja.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wartości.
        /// </summary>
        public static string Mission2 {
            get {
                return ResourceManager.GetString("Mission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Misja.
        /// </summary>
        public static string MissionHeader1 {
            get {
                return ResourceManager.GetString("MissionHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wizja.
        /// </summary>
        public static string MissionHeader2 {
            get {
                return ResourceManager.GetString("MissionHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pasja.
        /// </summary>
        public static string MissionHeader3 {
            get {
                return ResourceManager.GetString("MissionHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Skuteczność.
        /// </summary>
        public static string MissionHeader4 {
            get {
                return ResourceManager.GetString("MissionHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wiedza i doświadczenie.
        /// </summary>
        public static string MissionHeader5 {
            get {
                return ResourceManager.GetString("MissionHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Partnerstwo i uczciwość.
        /// </summary>
        public static string MissionHeader6 {
            get {
                return ResourceManager.GetString("MissionHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generujemy realne korzyści dla naszych klientów, zapewniając im zwrot z inwestycji poprzez projektowanie i wdrażanie skutecznych rozwiązań..
        /// </summary>
        public static string MissionText1 {
            get {
                return ResourceManager.GetString("MissionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jesteśmy dostawcą realnych korzyści, zapewniamy praktyczne rozwiązania. Korzystanie z naszych usług przynosi klientom zwrot z inwestycji poprzez zwiększanie zadowolenie, kreatywność i efektywność pracowników, podnosi wydajność całej organizacji. Jesteśmy dla siebie stałymi partnerami we wspólnym rozwoju..
        /// </summary>
        public static string MissionText2 {
            get {
                return ResourceManager.GetString("MissionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to To, co robimy jest naszą pasją. Robimy to z zaangażowaniem i radością..
        /// </summary>
        public static string MissionText3 {
            get {
                return ResourceManager.GetString("MissionText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rezultat naszej pracy przynosi firmom i klientom realne korzyści. Słowem kluczem jest dla nas zwrot z inwestycji (ROI). Osiąganie zamierzonych wyników stanowi o naszej odpowiedzialności i zaangażowaniu..
        /// </summary>
        public static string MissionText4 {
            get {
                return ResourceManager.GetString("MissionText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jesteśmy profesjonalistami. Uczymy się nieustannie i wspieramy firmy oraz ludzi w ich rozwoju.
        ///Na potrzeby różnych projektów pracują z nami kompetentni współpracownicy..
        /// </summary>
        public static string MissionText5 {
            get {
                return ResourceManager.GetString("MissionText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ludzie są dla nas kluczowi i znajdują się zawsze w centrum naszego zainteresowania. Traktujemy siebie z szacunkiem. I uczciwością..
        /// </summary>
        public static string MissionText6 {
            get {
                return ResourceManager.GetString("MissionText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dla kogo.
        /// </summary>
        public static string ToWho {
            get {
                return ResourceManager.GetString("ToWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Pracujemy z klientami biznesowymi, małymi i dużymi firmami, firmami jednoosobowymi, posiadającymi lub nie, świadomość konieczności rozwoju lub określenia potrzeb rozwojowych. Pracujemy z klientami indywidualnymi, osobami fizycznymi - absolwenci szkół wyższych i osoby pracujące zawodowo, którzy chcą rozwijać się na polu osobistym i zawodowym, często osiągnąć lepszą pozycję na rynku pracy. Ofertę kierujemy do wszystkich mających potrzebę nabycia i rozwoju wiedzy, umiejętności, zachowań, postaw. Do wszystkich  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ToWhoText1 {
            get {
                return ResourceManager.GetString("ToWhoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zapraszamy.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli zarządzasz Firmą, która nie ma wewnętrznego działu HR, ale szukasz rozwiązania w tym obszarze, zapraszamy!.
        /// </summary>
        public static string WelcomeText1 {
            get {
                return ResourceManager.GetString("WelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli zarządzasz Firmą, która posiada wewnętrzny dział HR, ale chciałbyś podnieść jego standardy i zwiększyć jego efektywność i przełożenie na biznes, zapraszamy!.
        /// </summary>
        public static string WelcomeText2 {
            get {
                return ResourceManager.GetString("WelcomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli zarządzasz Firmą, która posiada wewnętrzny dział HR, ale chciałbyś outsource’ować jego część, zapraszamy!.
        /// </summary>
        public static string WelcomeText3 {
            get {
                return ResourceManager.GetString("WelcomeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli jako prezes lub dyrektor, szukasz kompleksowego rozwiązania z obszaru HR lub IT dla swojej Firmy, chcesz mieć pewność zwrotu z inwestycji oraz prostej i miłej obsługi, zapraszamy!.
        /// </summary>
        public static string WelcomeText4 {
            get {
                return ResourceManager.GetString("WelcomeText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli jako menedżer wyższego lub niższego szczebla nie masz czasu albo nie chcesz uczyć swoich pracowników, a jednocześnie oczekujesz od nich lepszych rezultatów pracy i lepszego wyniku finansowego dla Firmy, zapraszamy!.
        /// </summary>
        public static string WelcomeText5 {
            get {
                return ResourceManager.GetString("WelcomeText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli jako menedżer HR, potrzebujesz wsparcia we wdrażaniu nowych rozwiązań i pomysłów, chcesz w pełni pracować jako biznes partner i konkretnie wesprzeć biznesową działalność firmy, przy zachowaniu zwrotu z inwestycji, zapraszamy!.
        /// </summary>
        public static string WelcomeText6 {
            get {
                return ResourceManager.GetString("WelcomeText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli jako menedżer HR potrzebujesz szkoleń dla swoich pracowników, bo oczekujesz od nich biznesowego podejścia i nastawienia na wsparcie wewnętrznego klienta, zapraszamy!.
        /// </summary>
        public static string WelcomeText7 {
            get {
                return ResourceManager.GetString("WelcomeText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli szukasz efektywnego szkolenia, które będzie inkubatorem pomysłów i rozwiązań, które pozwoli na rozwój konkretnych umiejętności i postaw, skutkujących konkretnymi nowymi, lepszymi działaniami w miejscu pracy, zapraszamy!.
        /// </summary>
        public static string WelcomeText8 {
            get {
                return ResourceManager.GetString("WelcomeText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jeśli znajdujesz się w sytuacji kryzysowej, nie wiesz co zrobić w obecnej sytuacji osobistej bądź zawodowej albo chcesz rozwinąć swoje umiejętności, zmienić podejście do życia i pracy, zapraszamy!.
        /// </summary>
        public static string WelcomeText9 {
            get {
                return ResourceManager.GetString("WelcomeText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Co oferujemy.
        /// </summary>
        public static string WhatWeDo {
            get {
                return ResourceManager.GetString("WhatWeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Oferujemy skuteczne rozwiązania doradcze, szkoleniowe, coachingowe oraz rozwiania twarde z zakresu różnorodnych rozwiązań informatycznych B2B i Business Intelligence. Oferta nasza jest owocem przeszło 15-letniego okresu zdobywania doświadczenia, wiedzy i umiejętności z zakresu zarządzania, ekonomii, psychologii, HR, oraz rozwiązań IT. Oferujemy sprawdzone rozwiązania w atrakcyjnych cenach z gwarancją zapewniającą zleceniodawcy realne korzyści osiągnięcia sukcesu w określonych ważnych dla niego obszarach i z [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhatWeDoText1 {
            get {
                return ResourceManager.GetString("WhatWeDoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dlaczego my.
        /// </summary>
        public static string WhyWe {
            get {
                return ResourceManager.GetString("WhyWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Potrafimy osiągać sukcesy w realizacji ambitnych, realnych, konkretnych i mierzalnych celów ustalonych z klientem biznesowym lub indywidualnym. Mamy do tego wewnętrzną – niezależną od otoczenia – motywację, której sprzyjają wyznawane przez nas wartości. Wiemy, jakie są kluczowe czynniki sukcesu efektywnego działania biznesowego dzięki dotychczasowej współpracy z doświadczonymi menedżerami z najwyższych szczebli zarządzania. Umiemy wyliczać efektywność prowadzonych przez nas działań i przekładać je na mierni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhyWeText1 {
            get {
                return ResourceManager.GetString("WhyWeText1", resourceCulture);
            }
        }
    }
}
