//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPrivacy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResPrivacy() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResPrivacy", typeof(ResPrivacy).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2. Informacje o plikach cookies.
        /// </summary>
        public static string CookiesHeader {
            get {
                return ResourceManager.GetString("CookiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2.1 Serwis korzysta z plików cookies..
        /// </summary>
        public static string CookiesItem1 {
            get {
                return ResourceManager.GetString("CookiesItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2.2 Pliki cookies (tzw. „ciasteczka”) stanowią dane informatyczne, w szczególności pliki tekstowe, które przechowywane są w urządzeniu końcowym Użytkownika Serwisu i przeznaczone są do korzystania ze stron internetowych Serwisu. Cookies zazwyczaj zawierają nazwę podaną przez stronę internetową, z której pochodzą, czas przechowywania ich na urządzeniu końcowym oraz ich przypisaną wartość..
        /// </summary>
        public static string CookiesItem2 {
            get {
                return ResourceManager.GetString("CookiesItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  2.3 W ramach Serwisu stosowane są dwa zasadnicze rodzaje plików cookies: „sesyjne” (session cookies) oraz „stałe” (persistent cookies). Cookies „sesyjne” są plikami tymczasowymi, które przechowywane są w urządzeniu końcowym Użytkownika do czasu wylogowania, opuszczenia strony internetowej lub wyłączenia oprogramowania (przeglądarki internetowej). „Stałe” pliki cookies przechowywane są w urządzeniu końcowym Użytkownika przez czas określony w parametrach plików cookies lub do czasu ich usunięcia przez Użytkow [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CookiesItem3 {
            get {
                return ResourceManager.GetString("CookiesItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  2.4 W ramach Serwisu stosowane mogą być cookis służące do dostosowania zawartości stron internetowych Serwisu do preferencji Użytkownika. Do optymalizacji korzystania ze stron internetowych Serwisu oraz realizacji procesów niezbędnych dla pełnej funkcjonalności Serwisu. Do zapamiętania ustawień wybranych przez Użytkownika i personalizacji interfejsu Użytkownika, np. w zakresie wybranego języka lub regionu, z którego pochodzi Użytkownik. Do utrzymania sesji Użytkownika Serwisu, dzięki której Użytkownik nie m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CookiesItem4 {
            get {
                return ResourceManager.GetString("CookiesItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2.5 W ramach Serwisu stosowane mogą być cookis służące do zbierania ogólnych i anonimowych danych statycznych za pośrednictwem narzędzi analitycznych Google Analytics, które pomagają zrozumieć, w jaki sposób Użytkownicy Serwisu korzystają ze stron internetowych Serwisu, co umożliwia ulepszanie ich struktury i zawartości. Podmiotem zamieszczającym na urządzeniu końcowym Użytkownika tego rodzaju pliki cookies oraz uzyskującym do nich dostęp jest Google Inc z siedzibą w USA..
        /// </summary>
        public static string CookiesItem5 {
            get {
                return ResourceManager.GetString("CookiesItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2.6 Oprogramowanie do przeglądania stron internetowych (przeglądarka internetowa) zazwyczaj domyślnie dopuszcza przechowywanie plików cookies w urządzeniu końcowym Użytkownika. Użytkownicy Serwisu mogą dokonać zmiany ustawień w tym zakresie. Przeglądarka internetowa umożliwia usunięcie plików cookies. Możliwe jest także automatyczne blokowanie plików cookies Szczegółowe informacje na ten temat zawiera pomoc lub dokumentacja przeglądarki internetowej..
        /// </summary>
        public static string CookiesItem6 {
            get {
                return ResourceManager.GetString("CookiesItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2.7 Operator Serwisu informuje, że ograniczenie stosowania plików cookies może wpłynąć na niektóre funkcjonalności dostępne na stronach internetowych Serwisu..
        /// </summary>
        public static string CookiesItem7 {
            get {
                return ResourceManager.GetString("CookiesItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  2.8 Użytkownik może samodzielnie i w każdym czasie zmienić ustawienia dotyczące plików cookies, określając warunki ich przechowywania i uzyskiwania dostępu przez pliki Cookies do Urządzenia Użytkownika. Zmiany ustawień, o których mowa w zdaniu poprzednim, Użytkownik może dokonać za pomocą ustawień przeglądarki internetowej (np. w sekcji „Ustawienia” lub „Pomoc”). Zastrzegamy, że wyłączenie obsługi plików cookies niezbędnych dla procesów uwierzytelniania, bezpieczeństwa, utrzymania preferencji użytkownika mo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CookiesItem8 {
            get {
                return ResourceManager.GetString("CookiesItem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 3. Informacje o formularzach.
        /// </summary>
        public static string FormHeader {
            get {
                return ResourceManager.GetString("FormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 3.1 Serwis zbiera informacje podane dobrowolnie przez użytkownika w formularzach..
        /// </summary>
        public static string FormItem1 {
            get {
                return ResourceManager.GetString("FormItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 3.2 Dane w formularzach nie są udostępniane podmiotom trzecim..
        /// </summary>
        public static string FormItem2 {
            get {
                return ResourceManager.GetString("FormItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 3.3 Dane podane w formularzach są przetwarzane w celu wynikającym z funkcji konkretnego formularza, np. w celu dokonania procesu obsługi zgłoszenia serwisowego lub kontaktu handlowego..
        /// </summary>
        public static string FormItem3 {
            get {
                return ResourceManager.GetString("FormItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 3.4 Dane podane w formularzach mogą być przekazane podmiotom technicznie realizującym niektóre usługi, np. konta mailowe Operatora Serwisu..
        /// </summary>
        public static string FormItem4 {
            get {
                return ResourceManager.GetString("FormItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 1. Informacje ogólne.
        /// </summary>
        public static string GeneralHeder {
            get {
                return ResourceManager.GetString("GeneralHeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 1.1 Operatorem Serwisu www.helobis.pl jest firma Helobis Agnieszka Jaśkiewicz z siedzibą w Warszawie 02-972, ul. Sarmacka 1B/167, NIP: PL9481999328, Regon: 147063096..
        /// </summary>
        public static string GeneralItem1 {
            get {
                return ResourceManager.GetString("GeneralItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 1.2 Serwis realizuje funkcje pozyskiwania informacji o Użytkowniku Serwisu i jego zachowaniu poprzez zapisywanie w urządzeniach końcowych pliki cookie (tzw. &quot;ciasteczka&quot;), poprzez dobrowolnie wprowadzone w formularzach informacje przez Użytkownika, poprzez gromadzenie logów serwera www przez Operatora tego Serwisu..
        /// </summary>
        public static string GeneralItem2 {
            get {
                return ResourceManager.GetString("GeneralItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Polityka Prywatności Serwisu www.helobis.pl.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nasz Serwis używa plików cookies („ciasteczek”) i innych technologii w celach statystycznych i do zapamiętywania ustawień Serwisu. Więcej informacji można znaleźć w naszej.
        /// </summary>
        public static string PrivacyDiv {
            get {
                return ResourceManager.GetString("PrivacyDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityce prywatności.
        /// </summary>
        public static string PrivacyLink {
            get {
                return ResourceManager.GetString("PrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 4. Informacje o plikach log serwera.
        /// </summary>
        public static string ServerHeader {
            get {
                return ResourceManager.GetString("ServerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 4.1 Informacje o niektórych zachowaniach użytkowników podlegają logowaniu w warstwie serwerowej. Dane te są wykorzystywane wyłącznie w celu administrowania serwisem oraz w celu zapewnienia jak najbardziej sprawnej obsługi świadczonych usług hostingowych..
        /// </summary>
        public static string ServerItem1 {
            get {
                return ResourceManager.GetString("ServerItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  4.2 Przeglądane zasoby identyfikowane są poprzez adresy URL. Ponadto zapisowi mogą podlegać: (a) czas nadejścia zapytania, (b) czas wysłania odpowiedzi, (c) nazwę stacji klienta – identyfikacja realizowana przez protokół HTTP, (d) informacje o błędach, jakie nastąpiły przy realizacji transakcji http, (e) adres URL strony poprzednio odwiedzanej przez użytkownika (referer link) – w przypadku, gdy przejście do Serwisu nastąpiło przez odnośnik (f) informacje o przeglądarce użytkownika, (g) Informacje o adresie  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServerItem2 {
            get {
                return ResourceManager.GetString("ServerItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 4.3 Dane powyższe nie są kojarzone z konkretnymi osobami przeglądającymi strony..
        /// </summary>
        public static string ServerItem3 {
            get {
                return ResourceManager.GetString("ServerItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 4.4 Dane powyższe są wykorzystywane jedynie dla celów administrowania serwerem..
        /// </summary>
        public static string ServerItem4 {
            get {
                return ResourceManager.GetString("ServerItem4", resourceCulture);
            }
        }
    }
}
