//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResRules() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResRules", typeof(ResRules).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dzięki naszej ofercie zapewnimy firmom wymagane dokumenty i spokój w obliczu kontroli zewnętrznej i wewnętrznej, która sprawdza istnienie i poprawność dokumentów. Szybka usługa za atrakcyjną cenę, opracowana zgodnie z wymogami i standardami rynku. Oszczędność czasu i pieniędzy dla zleceniodawcy. Spokój w obliczu kontroli zewnętrznej i zapobieżenie ewentualnym karom za brak posiadanych dokumentów lub błędy w dokumentach istniejących..
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Regulaminy, polityki, procedury to obowiązkowe dokumenty, które muszą istnieć w każdej firmie zatrudniającej powyżej 20 osób. Korzystając z naszych kilkunastoletnich doświadczeń w zakresie opracowywania wyżej wymienionych dokumentów, sprawiamy, że są one maksymalnie użyteczne, napisane w sposób prosty i przejrzysty. Ich wartością jest to, że przyczyniają się do realizacji strategii personalnej i biznesowej firmy, stanowią wsparcie dla procesów zarządzania firmą. Dokumenty te zapewniają firmom spójność konkr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityka i procedury rekrutacji pracowników.
        /// </summary>
        public static string ExapmlesList1Item1 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityka rozwoju pracowników.
        /// </summary>
        public static string ExapmlesList1Item2 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityka i procedury szkoleniowe.
        /// </summary>
        public static string ExapmlesList1Item3 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityka i procedura awansowania.
        /// </summary>
        public static string ExapmlesList1Item4 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityka przeciwdziałania mobbing’owi.
        /// </summary>
        public static string ExapmlesList1Item5 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to regulamin zakładowego funduszu świadczeń socjalnych.
        /// </summary>
        public static string ExapmlesList1Item6 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to polityka i regulaminy wynagrodzeń.
        /// </summary>
        public static string ExapmlesList1Item7 {
            get {
                return ResourceManager.GetString("ExapmlesList1Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regulaminy, Polityki, Procedury.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
