//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTraining {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResTraining() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResTraining", typeof(ResTraining).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Dzięki szkoleniom zapewnimy odbiorcom biznesowym i indywidualnym, praktyczną wiedzę, konkretne umiejętności, pożądane przez zleceniodawców zachowania i postawy w określonych obszarach. Szkolenia są doszywane do potrzeb klienta, po dokładnej analizie jego potrzeb. Szkolenia są nastawione na praktyczną naukę (mają formę praktycznego angażującego uczestników warsztatu), która ma swój indywidualny dla każdego uczestnika ciąg dalszy, w postaci zindywidualizowanego planu działań rozwojowych. Szkolenia zawsze stan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Klienci indywidualni zdobywają nową jakość w życiu osobistym i znajdują odpowiedzi na swoje potrzeby. Klienci biznesowi zrealizują efektywniej swoje zadania zawodowe (najczęściej określone w formie celów premiowych), za które otrzymują określoną premię. Oraz zrealizują swoje cele biznesowe, bezpośrednio przekładające się na mierniki efektywności, takie jak rentowność, cash flow (płynność finansowa), zysk..
        /// </summary>
        public static string BenefitsText2 {
            get {
                return ResourceManager.GetString("BenefitsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Nasze produkty szkoleniowe dedykowane są zarówno do osób fizycznych (szkolenia otwarte), jak i do klienta biznesowego (szkolenia otwarte i zamknięte). Szkolenia otwarte to szkolenia „gotowe” dla osób fizycznych (klientów indywidualnych). Szkolenia „zamknięte” to szkolenia dla firm, które za każdym razem są wstępnie zdefiniowane, ale zawsze są „doszywane” do konkretnych potrzeb klienta biznesowego, jego oczekiwań i celów, specyfiki grupy. Ze zdecydowanym akcentem położonym na wbudowanie szkolenia w proces ro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Metody, które stosujemy podczas pracy szkoleniowej to: ćwiczenia indywidualne i zespołowe, odgrywanie ról, prezentacje, inspiracja (teoria) poparta licznymi przykładami z życia w celu minimalizacji teorii, jako takiej, dyskusje prowadzone przez trenera w oparciu o doświadczenia i potrzeby uczestników, interakcje, informacja zwrotna udzielana na bieżąco, praca z kamerą praca na autentycznych dokumentach i przypadkach (tzw. Case Studies), zadania wdrożeniowe i indywidualne plany działania po szkoleniu..
        /// </summary>
        public static string CharacteristicsText2 {
            get {
                return ResourceManager.GetString("CharacteristicsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Akademia Młodego Szefa.
        /// </summary>
        public static string Example1Haeder {
            get {
                return ResourceManager.GetString("Example1Haeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ABC Menedżera (4 podstawowe funkcje zarządzania).
        /// </summary>
        public static string Example1Item1 {
            get {
                return ResourceManager.GetString("Example1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Komunikacja z współpracownikami, podwładnymi i przełożonym.
        /// </summary>
        public static string Example1Item2 {
            get {
                return ResourceManager.GetString("Example1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Budowa i zarządzanie zespołem.
        /// </summary>
        public static string Example1Item3 {
            get {
                return ResourceManager.GetString("Example1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Efektywne planowanie i organizowanie pracy zespołu i własnej.
        /// </summary>
        public static string Example1Item4 {
            get {
                return ResourceManager.GetString("Example1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Budowanie celów zespołu i motywujące rozliczanie ich realizacji.
        /// </summary>
        public static string Example1Item5 {
            get {
                return ResourceManager.GetString("Example1Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Akademia Doświadczonego Szefa.
        /// </summary>
        public static string Example2Haeder {
            get {
                return ResourceManager.GetString("Example2Haeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Budowanie autorytetu szefa.
        /// </summary>
        public static string Example2Item1 {
            get {
                return ResourceManager.GetString("Example2Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie ludźmi, czyli jak znajdować, zatrudniać, utrzymywać, wynagradzać i rozwijać najlepszych pracowników. I zwalniać najgorszych.
        /// </summary>
        public static string Example2Item2 {
            get {
                return ResourceManager.GetString("Example2Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O motywacji, czyli jak wyzwalać zaangażowanie innych.
        /// </summary>
        public static string Example2Item3 {
            get {
                return ResourceManager.GetString("Example2Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Szef mentorem i coach&apos;em.
        /// </summary>
        public static string Example2Item4 {
            get {
                return ResourceManager.GetString("Example2Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie konfliktem, czyli jak radzić sobie z trudnym pracownikiem, klientem, sprzecznymi interesami zespołów.
        /// </summary>
        public static string Example2Item5 {
            get {
                return ResourceManager.GetString("Example2Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Akademia Szefa Sprzedaży.
        /// </summary>
        public static string Example3Haeder {
            get {
                return ResourceManager.GetString("Example3Haeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Idę na spotkanie sprzedażowe a tego nie da się sprzedać, czyli o sztuce komunikacji i przekonywania i sile wewnętrznych przekonań.
        /// </summary>
        public static string Example3Item1 {
            get {
                return ResourceManager.GetString("Example3Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jak oni zrealizują ten mój plan sprzedażowy, czyli efektywne zarządzanie zespołem sprzedażowym.
        /// </summary>
        public static string Example3Item2 {
            get {
                return ResourceManager.GetString("Example3Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Żeby się chciało chcieć, czyli o motywowaniu sprzedawców.
        /// </summary>
        public static string Example3Item3 {
            get {
                return ResourceManager.GetString("Example3Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jak to robi najlepszy sprzedawca, czyli jak zarządzać dzieleniem się wiedzą w zespole sprzedażowym.
        /// </summary>
        public static string Example3Item4 {
            get {
                return ResourceManager.GetString("Example3Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Train the Trainers, czyli jak uczyć innych efektywnego sprzedawania.
        /// </summary>
        public static string Example3Item5 {
            get {
                return ResourceManager.GetString("Example3Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Akademia Efektywnego HR-owca.
        /// </summary>
        public static string Example4Haeder {
            get {
                return ResourceManager.GetString("Example4Haeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to HR w służbie biznesu, czyli o roli HR Biznes Partnera w firmie.
        /// </summary>
        public static string Example4Item1 {
            get {
                return ResourceManager.GetString("Example4Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie rozwojem i szkoleniami w organizacji, czyli jak realizować cele biznesowe i zarządzać budżetem. Cztery poziomy pomiaru efektywności działań rozwojowych.
        /// </summary>
        public static string Example4Item2 {
            get {
                return ResourceManager.GetString("Example4Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Biblioteka produktów rozwojowych, czyli jak wdrożyć bez kosztowy rozwój i zarządzanie wiedzą w firmie.
        /// </summary>
        public static string Example4Item3 {
            get {
                return ResourceManager.GetString("Example4Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Efektywne rozmowy HR-owca cz. 1 - czyli jak rozmawiać z biznesem, executive HR, zespołem HR oraz z podwykonawcami.
        /// </summary>
        public static string Example4Item4 {
            get {
                return ResourceManager.GetString("Example4Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Efektywne rozmowy HR-owca cz. 2 - czyli jak prowadzić rozmowy rekrutacyjne, rozwojowe i exit interview.
        /// </summary>
        public static string Example4Item5 {
            get {
                return ResourceManager.GetString("Example4Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pozostałe szkolenia.
        /// </summary>
        public static string Example5Haeder {
            get {
                return ResourceManager.GetString("Example5Haeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jak dostać tę robotę, czyli kompleksowe przygotowanie do rozmowy o pracę (w tym stylizacja i wizaż, analiza swoich mocnych i słabych stron, symulacje możliwych rozmów, opracowanie profesjonalnego cv i listu motywacyjnego) – praca z kamerą.
        /// </summary>
        public static string Example5Item1 {
            get {
                return ResourceManager.GetString("Example5Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jak cię widzą, tak cię piszą, czyli autoprezentacja i wystąpienia publiczne – praca z kamerą.
        /// </summary>
        public static string Example5Item2 {
            get {
                return ResourceManager.GetString("Example5Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzanie stresem, czyli nie taki diabeł straszny jak go malują.
        /// </summary>
        public static string Example5Item3 {
            get {
                return ResourceManager.GetString("Example5Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jak zarządzić tym, co nieuniknione, czyli radzenie sobie z kryzysami w życiu.
        /// </summary>
        public static string Example5Item4 {
            get {
                return ResourceManager.GetString("Example5Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Efektywność osobista, czyli z pustego i Salomon nie naleje - o zarządzaniu sobą w czasie.
        /// </summary>
        public static string Example5Item5 {
            get {
                return ResourceManager.GetString("Example5Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Oraz inne szkolenia dostosowane do potrzeb klienta.
        /// </summary>
        public static string Example5Item6 {
            get {
                return ResourceManager.GetString("Example5Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Obszary objęte szkoleniami.
        /// </summary>
        public static string ExamplesBoxHeder {
            get {
                return ResourceManager.GetString("ExamplesBoxHeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to zarządzania biznesem: dla szefów, kierowników, menedżerów, liderów, właścicieli jednoosobowych bądź małych/średnich/dużych przedsiębiorstw.
        /// </summary>
        public static string ExamplesBoxItem1 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to zarządzanie sprzedażą: dla sprzedawców, handlowców, przedstawicieli handlowych, szefów regionu, dyrektorów sprzedaży.
        /// </summary>
        public static string ExamplesBoxItem2 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to zarządzanie obszarami merytorycznymi HR: dla specjalistów, doradców HR, ekspertów, szefów projektów, kierowników.
        /// </summary>
        public static string ExamplesBoxItem3 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rozwój osobisty: dla każdego zainteresowanego własnym rozwojem.
        /// </summary>
        public static string ExamplesBoxItem4 {
            get {
                return ResourceManager.GetString("ExamplesBoxItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Szkolenia otwarte i zamknięte.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
