//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helobis.Hr.Web.Site.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResTests() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helobis.Hr.Web.Site.Resources.ResTests", typeof(ResTests).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wspiera rozwój osób i organizacji.
        /// </summary>
        public static string Advantages1Item1 {
            get {
                return ResourceManager.GetString("Advantages1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jest mało czasochłonny i prosty w obsłudze.
        /// </summary>
        public static string Advantages1Item2 {
            get {
                return ResourceManager.GetString("Advantages1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Daje wiele możliwości generowania raportów.
        /// </summary>
        public static string Advantages1Item3 {
            get {
                return ResourceManager.GetString("Advantages1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Jest wysoce profesjonalny z uwagi na zastosowaną metodologię.
        /// </summary>
        public static string Advantages1Item4 {
            get {
                return ResourceManager.GetString("Advantages1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zapewnia szybką i wiarygodną informację o osobowościach osób badanych, które warunkują sukces zawodowy. Wiedza płynąca z kwestionariusza może mieć zastosowanie w :.
        /// </summary>
        public static string AdvantagesText1 {
            get {
                return ResourceManager.GetString("AdvantagesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pozostałe zalety kwestionariusza:.
        /// </summary>
        public static string AdvantagesText2 {
            get {
                return ResourceManager.GetString("AdvantagesText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pozwala decydentom na podjęcie dobrych jakościowo i szybkich decyzji biznesowych. W wielu procesach (np. w rekrutacji wewnętrznej, rozwoju talentów, awansach)..
        /// </summary>
        public static string BenefitsText1 {
            get {
                return ResourceManager.GetString("BenefitsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Test psychometryczny dla osób fizycznych i klienta biznesowego to kwestionariusz wspomagający diagnozę i analizę potrzeb rozwojowych klienta. W założeniu, głównie będzie stosowany w długofalowych procesach rozwoju, zawsze zakończony będzie udzieleniem uczestnikowi badania informacji zwrotnej o wyniku testu..
        /// </summary>
        public static string CharacteristicsText1 {
            get {
                return ResourceManager.GetString("CharacteristicsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Biorąc pod uwagę niektóre elementy charakteryzujące rynek, kwestionariusz będzie pomocny dla tych klientów, którzy nie mają doświadczeń w organizacji działań rozwojowych dla pracowników, nie widzą potrzeb rozwojowych, bądź nie do końca potrafią określić cel rozwojowy do osiągnięcia. Dzięki nowoczesnej konstrukcji narzędzia istnieje możliwość dostosowania kwestionariusza Dimensions do modelu kompetencyjnego (zakresu wymagań kompetencyjnych dla stanowisk istniejących w firmie) Klienta. Kwestionariusz osobowoś [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacteristicsText2 {
            get {
                return ResourceManager.GetString("CharacteristicsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kwestionariusz Dimensions daje możliwość wygenerowania wielu raportów interpretacyjnych, niezbędnych do wsparcia wielu procesów HR w organizacji. Kwestionariusz osobowości Dimensions został stworzony zgodnie z najwyższymi standardami naukowymi. System oceny spełnia najbardziej rygorystyczne standardy psychometryczne stworzone przez prof. Rogera Holdswortha, światowy autorytet w dziedzinie psychologii biznesu..
        /// </summary>
        public static string CharacteristicsText3 {
            get {
                return ResourceManager.GetString("CharacteristicsText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Na bazie jednego badania można wygenerować całą gamę raportów mających zastosowanie we wszystkich procesach HR  (m.in. rekrutacja, reorganizacja, rozwój osobisty, rozwój zespołu, coaching menedżerski i outplacement)..
        /// </summary>
        public static string CharacteristicsText4 {
            get {
                return ResourceManager.GetString("CharacteristicsText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kwestionariusz Dimensions posiada wbudowaną funkcję Kreatora Profilu Stanowiska, która umożliwia ocenę kandydatów w oparciu o wymagania dotyczące danego stanowiska. Uzupełnienie kwestionariusza Dimensions zajmuje zwykle 25 minut, co sprawia, że jest o wiele mniej czasochłonny niż większość testów osobowości. Kwestionariusz Dimensions dostępny jest w ponad 30 językach, co umożliwia prowadzenie globalnych projektów oceny..
        /// </summary>
        public static string CharacteristicsText5 {
            get {
                return ResourceManager.GetString("CharacteristicsText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Talent Q Dimensions Elements.
        /// </summary>
        public static string HeaderPart1 {
            get {
                return ResourceManager.GetString("HeaderPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kwestionariusz Osobowości.
        /// </summary>
        public static string HeaderPart2 {
            get {
                return ResourceManager.GetString("HeaderPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzaniu procesami biznesowymi.
        /// </summary>
        public static string Usage1Item1 {
            get {
                return ResourceManager.GetString("Usage1Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zarządzaniu procesami HR.
        /// </summary>
        public static string Usage1Item2 {
            get {
                return ResourceManager.GetString("Usage1Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rozwoju osobistym.
        /// </summary>
        public static string Usage1Item3 {
            get {
                return ResourceManager.GetString("Usage1Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pracy nad sobą podczas coachingu / mentoringu.
        /// </summary>
        public static string Usage1Item4 {
            get {
                return ResourceManager.GetString("Usage1Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Przygotowaniu do objęcia nowego stanowiska w drodze rozwoju zawodowego / następstwa / sukcesji / zmiany pracy.
        /// </summary>
        public static string Usage1Item5 {
            get {
                return ResourceManager.GetString("Usage1Item5", resourceCulture);
            }
        }
    }
}
